spring.application.name=quizapp
server.port=8081

app.admin.username=admin
app.admin.password=1234

#spring.datasource.url=jdbc:mysql://localhost:3306/quizdb
#spring.datasource.username=root
#spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kavithasakthivel5420@gmail.com
spring.mail.password=mmasoagfltymwska
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:postgresql://dpg-d7nfrbegvqtc73aqvtn0-a.oregon-postgres.render.com:5432/quizapp_db_5mju
spring.datasource.username=quizapp_db_5mju_user
spring.datasource.password=wzPGkhGanMfoiEqg61OSWDXKzETAEjyP
#postgresql://quizapp_db_kd2j_user:3SRoyOPwM42rtWQeLBXMwgimadkHkytP@dpg-d7kc05lckfvc73bj6rd0-a/quizapp_db_kd2j
#postgresql://quizapp_db_kd2j_user:3SRoyOPwM42rtWQeLBXMwgimadkHkytP@dpg-d7kc05lckfvc73bj6rd0-a.oregon-postgres.render.com/quizapp_db_kd2j
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

